name: anunciacion
description: "Sistema de GestiÃ³n Escolar - Clean Architecture"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.1.0
  get_it: ^7.6.7

  # Base de datos - PostgreSQL
  postgres: ^3.4.8
  
  # PDF y archivos
  pdf: ^3.10.4
  printing: ^5.11.0
  file_picker: ^6.1.1
  http: ^1.1.0
  syncfusion_flutter_pdf: ^24.1.41
  
  # File system access (required by some plugins)
  path_provider: ^2.1.1

  # State Management
  provider: ^6.1.1
  flutter_riverpod: ^2.4.9

  # Utilidades
  intl: ^0.19.0
  crypto: ^3.0.3
  uuid: ^4.2.1
  equatable: ^2.0.5
  url_launcher: ^6.2.2

  mobile_scanner: ^5.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/logoanunciacion.png
